trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
# Build the project 
- task: Maven@4
  inputs:
    mavenPomFile: 'famney/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

# Run unit tests 
- task: Maven@4
  displayName: 'Run unit tests'
  inputs:
    mavenPomFile: 'famney/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    goals: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

# Publish the entire target folder as artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'famney/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Download artifact before deployment
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    artifactName: 'drop'
    downloadPath: '$(Build.ArtifactStagingDirectory)'

# Deploy the WAR
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'famney-connection'
    appType: 'webApp'
    appName: 'famney'
    package: '$(Build.ArtifactStagingDirectory)/drop/famney.war'