name: Build and deploy WAR app to Azure Web App - famney

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn -f famney/pom.xml clean install

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EF33A91A55F44D1FA14D14D942FA4E04 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2B7ECD5F8CE04F4CA513355048E5FAFD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AFC3F97D227749EDB4A938636A95FCAD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'famney'
          slot-name: 'Production'
          package: 'famney/target/famney.war'
